services:
  - type: web
    name: simulados-ibgp
    env: python
    buildCommand: "pip install -r api/requirements.txt"
    startCommand: "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REBUILD_TRIGGER
        value: "2026-01-30-17:00"
